Iteration 0:
     _dd.di._eh : 1538890573
     _dd.di._er : NotEligible
Iteration 1:
     _dd.debug.error.0.frame_data.class_name : ExceptionCaughtAndRethrownAsInnerTest
     _dd.debug.error.0.frame_data.function : Run
     _dd.debug.error.0.snapshot_id : <Redacted>
     _dd.debug.error.2.frame_data.class_name : <RunTest>d__6
     _dd.debug.error.2.frame_data.function : MoveNext
     _dd.debug.error.2.snapshot_id : <Redacted>
     _dd.debug.error.3.frame_data.class_name : <RunTest>d__5
     _dd.debug.error.3.frame_data.function : MoveNext
     _dd.debug.error.3.snapshot_id : <Redacted>
     _dd.debug.error.exception_hash : <Redacted>
     _dd.debug.error.exception_id : <Redacted>
     _dd.di._eh : 1538890573
     _dd.di._er : Eligible
Iteration 2:
     _dd.di._eh : 1538890573
     _dd.di._er : CachedDoneExceptionCase
Iteration 3:
     _dd.di._eh : 1538890573
     _dd.di._er : CachedDoneExceptionCase
