[
  {
    TraceId: Id_1,
    SpanId: Id_2,
    Name: CustomTracingExceptionHandler.handle-async,
    Resource: CustomTracingExceptionHandler.handle-async,
    Service: sample/my-app,
    ParentId: Id_3,
    Tags: {
      env: integration_tests,
      language: dotnet,
      span.kind: server,
      version: 1.0.0
    }
  },
  {
    TraceId: Id_1,
    SpanId: Id_3,
    Name: aspnet.request,
    Resource: GET /api2/transientfailure/false,
    Service: sample/my-app,
    Type: web,
    Error: 1,
    Tags: {
      env: integration_tests,
      error.msg: Passed in value was not 'true': false,
      error.stack:
System.ArgumentException: Passed in value was not 'true': false
at Samples.AspNetMvc5.Controllers.ConventionsController.TransientFailure(String value),
      error.type: System.ArgumentException,
      http.client_ip: 127.0.0.1,
      http.method: GET,
      http.request.headers.host: localhost:00000,
      http.status_code: 500,
      http.url: http://localhost/my-app/api2/transientfailure/false,
      http.useragent: testhelper,
      language: dotnet,
      network.client.ip: ::1,
      runtime-id: Guid_1,
      span.kind: server,
      version: 1.0.0
    },
    Metrics: {
      process_id: 0,
      _dd.agent_psr: 1.0,
      _dd.top_level: 1.0,
      _dd.tracer_kr: 1.0,
      _sampling_priority_v1: 1.0
    }
  }
]