[
  {
    TraceId: Id_1,
    SpanId: Id_2,
    Name: aspnet_core.request,
    Resource: POST /dataapi/model,
    Service: Samples.Security.AspNetCore2,
    Type: web,
    Error: 1,
    Tags: {
      aspnet_core.route: dataapi/model,
      component: aspnet_core,
      env: integration_tests,
      error.msg: Attempt by method 'Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingResult)' to access method 'Datadog.Trace.ClrProfiler.CallTarget.CallTargetInvoker.LogException<Datadog.Trace.ClrProfiler.AspNetCore.DefaultModelBindingContext_Integration,Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext>(System.Exception)' failed.,
      error.stack:
System.MethodAccessException: Attempt by method 'Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingResult)' to access method 'Datadog.Trace.ClrProfiler.CallTarget.CallTargetInvoker.LogException<Datadog.Trace.ClrProfiler.AspNetCore.DefaultModelBindingContext_Integration,Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext>(System.Exception)' failed.
   at Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(ModelBindingResult value)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application),
      error.type: System.MethodAccessException,
      http.method: POST,
      http.request.headers.host: localhost:00000,
      http.status_code: 500,
      http.url: http://localhost:00000/dataapi/model,
      language: dotnet,
      runtime-id: Guid_1,
      span.kind: server
    },
    Metrics: {
      process_id: 0,
      _dd.top_level: 1.0,
      _dd.tracer_kr: 1.0,
      _sampling_priority_v1: 1.0
    }
  },
  {
    TraceId: Id_3,
    SpanId: Id_4,
    Name: aspnet_core.request,
    Resource: POST /dataapi/model,
    Service: Samples.Security.AspNetCore2,
    Type: web,
    Error: 1,
    Tags: {
      aspnet_core.route: dataapi/model,
      component: aspnet_core,
      env: integration_tests,
      error.msg: Attempt by method 'Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingResult)' to access method 'Datadog.Trace.ClrProfiler.CallTarget.CallTargetInvoker.LogException<Datadog.Trace.ClrProfiler.AspNetCore.DefaultModelBindingContext_Integration,Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext>(System.Exception)' failed.,
      error.stack:
System.MethodAccessException: Attempt by method 'Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingResult)' to access method 'Datadog.Trace.ClrProfiler.CallTarget.CallTargetInvoker.LogException<Datadog.Trace.ClrProfiler.AspNetCore.DefaultModelBindingContext_Integration,Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext>(System.Exception)' failed.
   at Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(ModelBindingResult value)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application),
      error.type: System.MethodAccessException,
      http.method: POST,
      http.request.headers.host: localhost:00000,
      http.status_code: 500,
      http.url: http://localhost:00000/dataapi/model,
      language: dotnet,
      runtime-id: Guid_1,
      span.kind: server
    },
    Metrics: {
      process_id: 0,
      _dd.top_level: 1.0,
      _dd.tracer_kr: 1.0,
      _sampling_priority_v1: 1.0
    }
  },
  {
    TraceId: Id_5,
    SpanId: Id_6,
    Name: aspnet_core.request,
    Resource: POST /dataapi/model,
    Service: Samples.Security.AspNetCore2,
    Type: web,
    Error: 1,
    Tags: {
      aspnet_core.route: dataapi/model,
      component: aspnet_core,
      env: integration_tests,
      error.msg: Attempt by method 'Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingResult)' to access method 'Datadog.Trace.ClrProfiler.CallTarget.CallTargetInvoker.LogException<Datadog.Trace.ClrProfiler.AspNetCore.DefaultModelBindingContext_Integration,Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext>(System.Exception)' failed.,
      error.stack:
System.MethodAccessException: Attempt by method 'Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingResult)' to access method 'Datadog.Trace.ClrProfiler.CallTarget.CallTargetInvoker.LogException<Datadog.Trace.ClrProfiler.AspNetCore.DefaultModelBindingContext_Integration,Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext>(System.Exception)' failed.
   at Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(ModelBindingResult value)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application),
      error.type: System.MethodAccessException,
      http.method: POST,
      http.request.headers.host: localhost:00000,
      http.status_code: 500,
      http.url: http://localhost:00000/dataapi/model,
      language: dotnet,
      runtime-id: Guid_1,
      span.kind: server
    },
    Metrics: {
      process_id: 0,
      _dd.top_level: 1.0,
      _dd.tracer_kr: 1.0,
      _sampling_priority_v1: 1.0
    }
  },
  {
    TraceId: Id_7,
    SpanId: Id_8,
    Name: aspnet_core.request,
    Resource: POST /dataapi/model,
    Service: Samples.Security.AspNetCore2,
    Type: web,
    Error: 1,
    Tags: {
      aspnet_core.route: dataapi/model,
      component: aspnet_core,
      env: integration_tests,
      error.msg: Attempt by method 'Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingResult)' to access method 'Datadog.Trace.ClrProfiler.CallTarget.CallTargetInvoker.LogException<Datadog.Trace.ClrProfiler.AspNetCore.DefaultModelBindingContext_Integration,Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext>(System.Exception)' failed.,
      error.stack:
System.MethodAccessException: Attempt by method 'Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingResult)' to access method 'Datadog.Trace.ClrProfiler.CallTarget.CallTargetInvoker.LogException<Datadog.Trace.ClrProfiler.AspNetCore.DefaultModelBindingContext_Integration,Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext>(System.Exception)' failed.
   at Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(ModelBindingResult value)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application),
      error.type: System.MethodAccessException,
      http.method: POST,
      http.request.headers.host: localhost:00000,
      http.status_code: 500,
      http.url: http://localhost:00000/dataapi/model,
      language: dotnet,
      runtime-id: Guid_1,
      span.kind: server
    },
    Metrics: {
      process_id: 0,
      _dd.top_level: 1.0,
      _dd.tracer_kr: 1.0,
      _sampling_priority_v1: 1.0
    }
  },
  {
    TraceId: Id_9,
    SpanId: Id_10,
    Name: aspnet_core.request,
    Resource: POST /dataapi/model,
    Service: Samples.Security.AspNetCore2,
    Type: web,
    Error: 1,
    Tags: {
      aspnet_core.route: dataapi/model,
      component: aspnet_core,
      env: integration_tests,
      error.msg: Attempt by method 'Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingResult)' to access method 'Datadog.Trace.ClrProfiler.CallTarget.CallTargetInvoker.LogException<Datadog.Trace.ClrProfiler.AspNetCore.DefaultModelBindingContext_Integration,Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext>(System.Exception)' failed.,
      error.stack:
System.MethodAccessException: Attempt by method 'Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(Microsoft.AspNetCore.Mvc.ModelBinding.ModelBindingResult)' to access method 'Datadog.Trace.ClrProfiler.CallTarget.CallTargetInvoker.LogException<Datadog.Trace.ClrProfiler.AspNetCore.DefaultModelBindingContext_Integration,Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext>(System.Exception)' failed.
   at Microsoft.AspNetCore.Mvc.ModelBinding.DefaultModelBindingContext.set_Result(ModelBindingResult value)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application),
      error.type: System.MethodAccessException,
      http.method: POST,
      http.request.headers.host: localhost:00000,
      http.status_code: 500,
      http.url: http://localhost:00000/dataapi/model,
      language: dotnet,
      runtime-id: Guid_1,
      span.kind: server
    },
    Metrics: {
      process_id: 0,
      _dd.top_level: 1.0,
      _dd.tracer_kr: 1.0,
      _sampling_priority_v1: 1.0
    }
  }
]